"use client";
import {useEffect,useMemo,useState} from "react";
import {BarChart3,Building2,CalendarDays,CircleDollarSign,LayoutDashboard,Menu,Plus,Search,Tags,Users,WalletCards,X} from "lucide-react";
type Entry={id:string;type:"INCOME"|"EXPENSE";description:string;party_name?:string;project_name?:string;category_name?:string;next_due_date?:string;total_cents:number;status:string};
type Dashboard={income_planned_cents:number;expense_planned_cents:number;income_realized_cents:number;expense_realized_cents:number;overdue_cents:number};
const zero:Dashboard={income_planned_cents:0,expense_planned_cents:0,income_realized_cents:0,expense_realized_cents:0,overdue_cents:0};
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(v||0)/100);
export default function Home(){
 const [d,setD]=useState(zero),[entries,setEntries]=useState<Entry[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[tab,setTab]=useState("Todos"),[query,setQuery]=useState(""),[nav,setNav]=useState(false);
 async function load(){setLoading(true);setError("");try{const [a,b]=await Promise.all([fetch("/api/dashboard"),fetch("/api/entries")]);const aj=await a.json(),bj=await b.json();if(!a.ok||!b.ok)throw new Error(aj.error||bj.error);setD(aj);setEntries(bj)}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar dados")}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 const list=useMemo(()=>entries.filter(e=>(tab==="Todos"||e.type===(tab==="Receitas"?"INCOME":"EXPENSE"))&&[e.description,e.party_name,e.project_name,e.category_name].join(" ").toLowerCase().includes(query.toLowerCase())),[entries,tab,query]);
 return <div className="shell"><aside className={nav?"sidebar open":"sidebar"}><div className="brand"><i>F</i><span><b>Fluxo</b><small>EVENTOS</small></span></div><button className="close" onClick={()=>setNav(false)}><X/></button><nav><a className="active"><LayoutDashboard/>Visão geral</a><a><WalletCards/>Financeiro</a><a><CalendarDays/>Eventos e projetos</a><a><Users/>Clientes e fornecedores</a><a><Tags/>Plano de contas</a><a><BarChart3/>Relatórios</a></nav><div className="bottom"><a><Building2/>Despesas internas</a><div className="profile"><i>TG</i><span><b>Administrador</b><small>Empresa de eventos</small></span></div></div></aside>
 <main className="content"><header><button className="hamb" onClick={()=>setNav(true)}><Menu/></button><div><p>Financeiro</p><h1>Receitas e despesas</h1></div><button className="primary"><Plus/>Novo lançamento</button></header>
 {error&&<section className="notice"><b>O painel está protegido e funcionando.</b><span>Falta configurar a conexão com o banco: {error}</span><button onClick={load}>Tentar novamente</button></section>}
 <section className="cards"><article className="featured"><span>Resultado previsto</span><strong>{money(Number(d.income_planned_cents)-Number(d.expense_planned_cents))}</strong><small>Receitas menos despesas cadastradas</small></article><article><span>Total de receitas</span><strong className="green">{money(d.income_planned_cents)}</strong><small>Previsto no período</small></article><article><span>Total de despesas</span><strong className="red">{money(d.expense_planned_cents)}</strong><small>Eventos e despesas internas</small></article><article><span>Valores vencidos</span><strong className="amber">{money(d.overdue_cents)}</strong><small>Contas que exigem atenção</small></article></section>
 <section className="split"><article><div className="section-title"><div><p>Visão da empresa</p><h2>Previsto × realizado</h2></div><CircleDollarSign/></div><div className="bars"><label>Receitas realizadas <b>{money(d.income_realized_cents)}</b><span><i style={{width:`${Math.min(100,Number(d.income_realized_cents)/(Number(d.income_planned_cents)||1)*100)}%`}}/></span></label><label>Despesas pagas <b>{money(d.expense_realized_cents)}</b><span className="expense"><i style={{width:`${Math.min(100,Number(d.expense_realized_cents)/(Number(d.expense_planned_cents)||1)*100)}%`}}/></span></label></div></article><article><p>Organização financeira</p><h2>Dois resultados separados</h2><div className="mini"><div><b>Eventos e projetos</b><span>Custos diretos, receitas e margem por evento.</span></div><div><b>Operação interna</b><span>Escritório, funcionários, veículos e tecnologia.</span></div></div></article></section>
 <section className="work"><div className="tabs">{["Todos","Receitas","Despesas"].map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="tools"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar lançamento, evento, cliente ou categoria"/></label></div><div className="table"><table><thead><tr><th>Vencimento</th><th>Lançamento</th><th>Evento / setor</th><th>Categoria</th><th>Situação</th><th>Valor</th></tr></thead><tbody>{list.map(e=><tr key={e.id}><td>{e.next_due_date?new Date(e.next_due_date+"T12:00").toLocaleDateString("pt-BR"):"—"}</td><td><b>{e.description}</b><small>{e.party_name||"Sem pessoa vinculada"}</small></td><td><em>{e.project_name||"Administração interna"}</em></td><td>{e.category_name||"—"}</td><td><span className="status">{e.status}</span></td><td className={e.type==="INCOME"?"green value":"red value"}>{e.type==="INCOME"?"+ ":"− "}{money(e.total_cents)}</td></tr>)}</tbody></table>{loading&&<div className="empty">Carregando informações financeiras…</div>}{!loading&&!list.length&&<div className="empty">Nenhum lançamento cadastrado ainda.</div>}</div></section>
 </main></div>
}