"use client";
import {useMemo,useState} from "react";
import {BarChart3,Building2,CalendarDays,CircleDollarSign,LayoutDashboard,Menu,Plus,Search,Tags,Users,WalletCards,X} from "lucide-react";
type Entry={id:string;type:"INCOME"|"EXPENSE";description:string;party:string;project:string;category:string;due:string;total:number;status:string};
const entries:Entry[]=[
{id:"1",type:"INCOME",description:"Parcela do contrato de produção",party:"Associação Cultural",project:"Festival do Japão 2026",category:"Contratos de produção",due:"18/09/2026",total:4850000,status:"Pendente"},
{id:"2",type:"EXPENSE",description:"Locação de painel de LED",party:"Visual Tech Eventos",project:"Festival do Japão 2026",category:"Audiovisual e LED",due:"16/09/2026",total:1280000,status:"Pago"},
{id:"3",type:"EXPENSE",description:"Equipe de recepção",party:"Equipe operacional",project:"Congresso Mulheres 2026",category:"Equipe e freelancers",due:"15/09/2026",total:360000,status:"Pendente"},
{id:"4",type:"INCOME",description:"Sinal do contrato",party:"Cliente Norte",project:"Inauguração Cliente Norte",category:"Contratos de produção",due:"10/09/2026",total:2200000,status:"Recebido"},
{id:"5",type:"EXPENSE",description:"Hospedagem VPS e sistemas",party:"Fornecedor de tecnologia",project:"Administração interna",category:"Softwares e tecnologia",due:"08/09/2026",total:89000,status:"Pago"}];
const brl=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v/100);
export default function Home(){
 const [tab,setTab]=useState("Todos"),[query,setQuery]=useState(""),[nav,setNav]=useState(false);
 const list=useMemo(()=>entries.filter(e=>(tab==="Todos"||e.type===(tab==="Receitas"?"INCOME":"EXPENSE"))&&Object.values(e).join(" ").toLowerCase().includes(query.toLowerCase())),[tab,query]);
 const income=entries.filter(e=>e.type==="INCOME").reduce((s,e)=>s+e.total,0),expense=entries.filter(e=>e.type==="EXPENSE").reduce((s,e)=>s+e.total,0);
 return <div className="shell"><aside className={nav?"sidebar open":"sidebar"}><div className="brand"><i>F</i><span><b>Fluxo</b><small>EVENTOS</small></span></div><button className="close" onClick={()=>setNav(false)}><X/></button><nav><a className="active"><LayoutDashboard/>Visão geral</a><a><WalletCards/>Financeiro</a><a><CalendarDays/>Eventos e projetos</a><a><Users/>Clientes e fornecedores</a><a><Tags/>Plano de contas</a><a><BarChart3/>Relatórios</a></nav><div className="bottom"><a><Building2/>Despesas internas</a><div className="profile"><i>TG</i><span><b>Modo demonstração</b><small>Dados fictícios</small></span></div></div></aside>
 <main className="content"><header><button className="hamb" onClick={()=>setNav(true)}><Menu/></button><div><p>Financeiro</p><h1>Receitas e despesas</h1></div><button className="primary"><Plus/>Novo lançamento</button></header>
 <section className="notice"><b>Versão de demonstração</b><span>Todos os valores e nomes desta tela são fictícios. Nenhum dado real está exposto.</span></section>
 <section className="cards"><article className="featured"><span>Resultado previsto</span><strong>{brl(income-expense)}</strong><small>Receitas menos despesas cadastradas</small></article><article><span>Total de receitas</span><strong className="green">{brl(income)}</strong><small>Contratos e entradas</small></article><article><span>Total de despesas</span><strong className="red">{brl(expense)}</strong><small>Eventos e despesas internas</small></article><article><span>Valores vencidos</span><strong className="amber">{brl(89000)}</strong><small>Contas que exigem atenção</small></article></section>
 <section className="split"><article><div className="section-title"><div><p>Visão da empresa</p><h2>Previsto × realizado</h2></div><CircleDollarSign/></div><div className="bars"><label>Receitas realizadas <b>{brl(2200000)}</b><span><i style={{width:"31%"}}/></span></label><label>Despesas pagas <b>{brl(1369000)}</b><span className="expense"><i style={{width:"79%"}}/></span></label></div></article><article><p>Organização financeira</p><h2>Dois resultados separados</h2><div className="mini"><div><b>Eventos e projetos</b><span>Custos diretos, receitas e margem por evento.</span></div><div><b>Operação interna</b><span>Escritório, funcionários, veículos e tecnologia.</span></div></div></article></section>
 <section className="work"><div className="tabs">{["Todos","Receitas","Despesas"].map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t}</button>)}</div><div className="tools"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar lançamento, evento, cliente ou categoria"/></label></div><div className="table"><table><thead><tr><th>Vencimento</th><th>Lançamento</th><th>Evento / setor</th><th>Categoria</th><th>Situação</th><th>Valor</th></tr></thead><tbody>{list.map(e=><tr key={e.id}><td>{e.due}</td><td><b>{e.description}</b><small>{e.party}</small></td><td><em>{e.project}</em></td><td>{e.category}</td><td><span className="status">{e.status}</span></td><td className={e.type==="INCOME"?"green value":"red value"}>{e.type==="INCOME"?"+ ":"− "}{brl(e.total)}</td></tr>)}</tbody></table>{!list.length&&<div className="empty">Nenhum lançamento encontrado.</div>}</div></section>
 </main></div>
}